In [3]:
import pandas as pd
import numpy as np

In [4]:
courses = pd.read_csv('courses.csv')
students = pd.read_csv('students.csv')
nov = pd.read_csv('reg-month1.csv')
dec = pd.read_csv('reg-month2.csv')

matches = pd.read_csv('matches.csv')
delivery = pd.read_csv('deliveries.csv')

In [5]:
pd.concat([nov,dec]) 
pd.concat([nov,dec],ignore_index=True)

    student_id     month registered
0            1   January         No
1            2   January         No
2            3   January         No
3            4   January        Yes
4            5   January         No
5            6   January         No
6            7   January        Yes
7            8   January        Yes
8            9   January        Yes
9           10   January        Yes
10          11   January         No
11          12   January         No
12          13   January         No
13          14   January         No
14          15   January         No
15          16   January         No
16          17   January        Yes
17          18   January         No
18          19   January        Yes
19          20   January        Yes
20          21   January         No
21          22   January        Yes
22          23   January         No
23          24   January        Yes
24          25   January         No
25          26   January        Yes
26          27   January         No
27          28   January         No
28          29   January         No
29          30   January         No
30           1  February         No
31           2  February        Yes
32           3  February        Yes
33           4  February        Yes
34           5  February         No
35           6  February        Yes
36           7  February         No
37           8  February         No
38           9  February        Yes
39          10  February        Yes
40          11  February         No
41          12  February        Yes
42          13  February         No
43          14  February         No
44          15  February         No
45          16  February         No
46          17  February         No
47          18  February        Yes
48          19  February        Yes
49          20  February         No
50          21  February         No
51          22  February        Yes
52          23  February        Yes
53          24  February         No
54          25  February        Yes
55          26  February         No
56          27  February        Yes
57          28  February         No
58          29  February        Yes
59          30  February         No

In [6]:
pd.concat([nov,dec],keys=['nov','dev'])

        student_id     month registered
nov 0            1   January         No
    1            2   January         No
    2            3   January         No
    3            4   January        Yes
    4            5   January         No
    5            6   January         No
    6            7   January        Yes
    7            8   January        Yes
    8            9   January        Yes
    9           10   January        Yes
    10          11   January         No
    11          12   January         No
    12          13   January         No
    13          14   January         No
    14          15   January         No
    15          16   January         No
    16          17   January        Yes
    17          18   January         No
    18          19   January        Yes
    19          20   January        Yes
    20          21   January         No
    21          22   January        Yes
    22          23   January         No
    23          24   January        Yes
    24          25   January         No
    25          26   January        Yes
    26          27   January         No
    27          28   January         No
    28          29   January         No
    29          30   January         No
dev 0            1  February         No
    1            2  February        Yes
    2            3  February        Yes
    3            4  February        Yes
    4            5  February         No
    5            6  February        Yes
    6            7  February         No
    7            8  February         No
    8            9  February        Yes
    9           10  February        Yes
    10          11  February         No
    11          12  February        Yes
    12          13  February         No
    13          14  February         No
    14          15  February         No
    15          16  February         No
    16          17  February         No
    17          18  February        Yes
    18          19  February        Yes
    19          20  February         No
    20          21  February         No
    21          22  February        Yes
    22          23  February        Yes
    23          24  February         No
    24          25  February        Yes
    25          26  February         No
    26          27  February        Yes
    27          28  February         No
    28          29  February        Yes
    29          30  February         No

In [7]:
#join['inner','outer','full',left,right]

In [8]:
students.merge(nov,how="inner",on="student_id")

    student_id        name  age  course  marks    month registered
0            1   Student_1   18  Python     99  January         No
1            2   Student_2   22     SQL     76  January         No
2            3   Student_3   29      ML     72  January         No
3            4   Student_4   20     SQL     47  January        Yes
4            5   Student_5   21      ML     92  January         No
5            6   Student_6   20     SQL     99  January         No
6            7   Student_7   18  Python     83  January        Yes
7            8   Student_8   18   Excel     83  January        Yes
8            9   Student_9   29  Python     44  January        Yes
9           10  Student_10   29   Excel     78  January        Yes
10          11  Student_11   22     SQL     43  January         No
11          12  Student_12   23      ML     45  January         No
12          13  Student_13   20  Python     84  January         No
13          14  Student_14   29   Excel     71  January         No
14          15  Student_15   26  Python     91  January         No
15          16  Student_16   22   Excel     69  January         No
16          17  Student_17   25  Python     86  January        Yes
17          18  Student_18   18   Excel     74  January         No
18          19  Student_19   22   Excel     94  January        Yes
19          20  Student_20   20     SQL     79  January        Yes
20          21  Student_21   29   Excel     91  January         No
21          22  Student_22   18     SQL     55  January        Yes
22          23  Student_23   21   Excel     52  January         No
23          24  Student_24   22      ML     89  January        Yes
24          25  Student_25   24      ML     99  January         No
25          26  Student_26   18      ML     81  January        Yes
26          27  Student_27   20   Excel     69  January         No
27          28  Student_28   19     SQL     58  January         No
28          29  Student_29   26     SQL     56  January         No
29          30  Student_30   27   Excel     95  January         No

In [9]:
students.merge(nov,how="left",on="student_id")

    student_id        name  age  course  marks    month registered
0            1   Student_1   18  Python     99  January         No
1            2   Student_2   22     SQL     76  January         No
2            3   Student_3   29      ML     72  January         No
3            4   Student_4   20     SQL     47  January        Yes
4            5   Student_5   21      ML     92  January         No
5            6   Student_6   20     SQL     99  January         No
6            7   Student_7   18  Python     83  January        Yes
7            8   Student_8   18   Excel     83  January        Yes
8            9   Student_9   29  Python     44  January        Yes
9           10  Student_10   29   Excel     78  January        Yes
10          11  Student_11   22     SQL     43  January         No
11          12  Student_12   23      ML     45  January         No
12          13  Student_13   20  Python     84  January         No
13          14  Student_14   29   Excel     71  January         No
14          15  Student_15   26  Python     91  January         No
15          16  Student_16   22   Excel     69  January         No
16          17  Student_17   25  Python     86  January        Yes
17          18  Student_18   18   Excel     74  January         No
18          19  Student_19   22   Excel     94  January        Yes
19          20  Student_20   20     SQL     79  January        Yes
20          21  Student_21   29   Excel     91  January         No
21          22  Student_22   18     SQL     55  January        Yes
22          23  Student_23   21   Excel     52  January         No
23          24  Student_24   22      ML     89  January        Yes
24          25  Student_25   24      ML     99  January         No
25          26  Student_26   18      ML     81  January        Yes
26          27  Student_27   20   Excel     69  January         No
27          28  Student_28   19     SQL     58  January         No
28          29  Student_29   26     SQL     56  January         No
29          30  Student_30   27   Excel     95  January         No
30          31  Student_31   23      ML     58      NaN        NaN
31          32  Student_32   27      ML     67      NaN        NaN
32          33  Student_33   20     SQL     97      NaN        NaN
33          34  Student_34   25      ML     94      NaN        NaN
34          35  Student_35   25  Python     65      NaN        NaN
35          36  Student_36   19     SQL     76      NaN        NaN
36          37  Student_37   23      ML     65      NaN        NaN
37          38  Student_38   24     SQL     92      NaN        NaN
38          39  Student_39   19  Python     62      NaN        NaN
39          40  Student_40   28     SQL     48      NaN        NaN
40          41  Student_41   27     SQL     51      NaN        NaN
41          42  Student_42   19     SQL     92      NaN        NaN
42          43  Student_43   27     SQL     40      NaN        NaN
43          44  Student_44   18  Python     97      NaN        NaN
44          45  Student_45   25   Excel     97      NaN        NaN
45          46  Student_46   18     SQL     40      NaN        NaN
46          47  Student_47   26     SQL     86      NaN        NaN
47          48  Student_48   28      ML     73      NaN        NaN
48          49  Student_49   23     SQL     71      NaN        NaN
49          50  Student_50   24      ML     93      NaN        NaN

In [14]:
students.merge(nov,how="right",on="student_id")
# on means the common column used to join both tables

    student_id        name   age  course  marks  partner    month registered
0            1   Student_1  18.0  Python   99.0      NaN  January         No
1            2   Student_2  22.0     SQL   76.0      NaN  January         No
2            3   Student_3  29.0      ML   72.0      NaN  January         No
3            4   Student_4  20.0     SQL   47.0      NaN  January        Yes
4            5   Student_5  21.0      ML   92.0      NaN  January         No
5            6   Student_6  20.0     SQL   99.0      NaN  January         No
6            7   Student_7  18.0  Python   83.0      NaN  January        Yes
7            8   Student_8  18.0   Excel   83.0      NaN  January        Yes
8            9   Student_9  29.0  Python   44.0      NaN  January        Yes
9           10  Student_10  29.0   Excel   78.0      NaN  January        Yes
10          11  Student_11  22.0     SQL   43.0      NaN  January         No
11          12  Student_12  23.0      ML   45.0      NaN  January         No
12          13  Student_13  20.0  Python   84.0      NaN  January         No
13          14  Student_14  29.0   Excel   71.0      NaN  January         No
14          15  Student_15  26.0  Python   91.0      NaN  January         No
15          16  Student_16  22.0   Excel   69.0      NaN  January         No
16          17  Student_17  25.0  Python   86.0      NaN  January        Yes
17          18  Student_18  18.0   Excel   74.0      NaN  January         No
18          19  Student_19  22.0   Excel   94.0      NaN  January        Yes
19          20  Student_20  20.0     SQL   79.0      NaN  January        Yes
20          21  Student_21  29.0   Excel   91.0      NaN  January         No
21          22  Student_22  18.0     SQL   55.0      NaN  January        Yes
22          23  Student_23  21.0   Excel   52.0      NaN  January         No
23          24  Student_24  22.0      ML   89.0      NaN  January        Yes
24          25  Student_25  24.0      ML   99.0      NaN  January         No
25          26  Student_26  18.0      ML   81.0      NaN  January        Yes
26          26      Nitish   NaN     NaN    NaN     28.0  January        Yes
27          27  Student_27  20.0   Excel   69.0      NaN  January         No
28          27       Ankit   NaN     NaN    NaN     26.0  January         No
29          28  Student_28  19.0     SQL   58.0      NaN  January         No
30          28       Rahul   NaN     NaN    NaN     17.0  January         No
31          29  Student_29  26.0     SQL   56.0      NaN  January         No
32          30  Student_30  27.0   Excel   95.0      NaN  January         No

In [11]:
temp_df = pd.DataFrame({
'student_id' : [26,27,28],
'name':['Nitish', 'Ankit','Rahul'],
'partner' : [28,26,17]

})

students = pd.concat([students, temp_df],ignore_index=True)

In [12]:
students.tail()

    student_id        name   age course  marks  partner
48          49  Student_49  23.0    SQL   71.0      NaN
49          50  Student_50  24.0     ML   93.0      NaN
50          26      Nitish   NaN    NaN    NaN     28.0
51          27       Ankit   NaN    NaN    NaN     26.0
52          28       Rahul   NaN    NaN    NaN     17.0

In [15]:
students.merge(nov,how="outer",on="student_id").tail()

    student_id        name   age course  marks  partner month registered
48          46  Student_46  18.0    SQL   40.0      NaN   NaN        NaN
49          47  Student_47  26.0    SQL   86.0      NaN   NaN        NaN
50          48  Student_48  28.0     ML   73.0      NaN   NaN        NaN
51          49  Student_49  23.0    SQL   71.0      NaN   NaN        NaN
52          50  Student_50  24.0     ML   93.0      NaN   NaN        NaN