In [8]:
"""what IS Pandas!

Pandas is an open-source Python library designed for data manipulation and analysis. It makes working with structured data fast, flexible, and intuitive - especially if you're dealing
with CSV files, Excel sheets, SQL tables, JSON, or APIs.

The two core data structures in Pandas are:

· Series : A 1D labeled array (like a column)
. DataFrame : A 2D labeled data structure (like a full spreadsheet or SQL table)

What Is a DataFrame?

A DataFrame is a two-dimensional, tabular data structure with labeled rows and columns. Think of it as a Python-native spreadsheet - but way more powerful and programmable.

Key Features:

· Label-based indexing
. Column-wise and row-wise operations
. Support for mixed data types
. Fast, vectorized operations (built on NumPy)


 """
import pandas as pd

In [9]:
df = pd.read_csv("deliveries.csv")

In [10]:
print(df)

        match_id  inning                 batting_team  \
0              1       1          Sunrisers Hyderabad
1              1       1          Sunrisers Hyderabad
2              1       1          Sunrisers Hyderabad
3              1       1          Sunrisers Hyderabad
4              1       1          Sunrisers Hyderabad
...          ...     ...                          ...
150455       636       2  Royal Challengers Bangalore
150456       636       2  Royal Challengers Bangalore
150457       636       2  Royal Challengers Bangalore
150458       636       2  Royal Challengers Bangalore
150459       636       2  Royal Challengers Bangalore

                       bowling_team  over  ball        batsman    non_striker  \
0       Royal Challengers Bangalore     1     1      DA Warner       S Dhawan
1       Royal Challengers Bangalore     1     2      DA Warner       S Dhawan
2       Royal Challengers Bangalore     1     3      DA Warner       S Dhawan
3       Royal Challengers Bangalore     1     4      DA Warner       S Dhawan
4       Royal Challengers Bangalore     1     5      DA Warner       S Dhawan
...                             ...   ...   ...            ...            ...
150455          Sunrisers Hyderabad    20     2    Sachin Baby      CJ Jordan
150456          Sunrisers Hyderabad    20     3    Sachin Baby      CJ Jordan
150457          Sunrisers Hyderabad    20     4  Iqbal Abdulla    Sachin Baby
150458          Sunrisers Hyderabad    20     5    Sachin Baby  Iqbal Abdulla
150459          Sunrisers Hyderabad    20     6  Iqbal Abdulla    Sachin Baby

          bowler  is_super_over  ...  bye_runs  legbye_runs  noball_runs  \
0       TS Mills              0  ...         0            0            0
1       TS Mills              0  ...         0            0            0
2       TS Mills              0  ...         0            0            0
3       TS Mills              0  ...         0            0            0
4       TS Mills              0  ...         0            0            0
...          ...            ...  ...       ...          ...          ...
150455   B Kumar              0  ...         0            0            0
150456   B Kumar              0  ...         0            0            0
150457   B Kumar              0  ...         0            1            0
150458   B Kumar              0  ...         0            0            0
150459   B Kumar              0  ...         0            0            0

        penalty_runs  batsman_runs  extra_runs  total_runs  player_dismissed  \
0                  0             0           0           0               NaN
1                  0             0           0           0               NaN
2                  0             4           0           4               NaN
3                  0             0           0           0               NaN
4                  0             0           2           2               NaN
...              ...           ...         ...         ...               ...
150455             0             2           0           2               NaN
150456             0             0           0           0         CJ Jordan
150457             0             0           1           1               NaN
150458             0             1           0           1               NaN
150459             0             4           0           4               NaN

       dismissal_kind  fielder
0                 NaN      NaN
1                 NaN      NaN
2                 NaN      NaN
3                 NaN      NaN
4                 NaN      NaN
...               ...      ...
150455            NaN      NaN
150456        run out  NV Ojha
150457            NaN      NaN
150458            NaN      NaN
150459            NaN      NaN

[150460 rows x 21 columns]

In [11]:
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [12]:
df.tail()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150460 entries, 0 to 150459
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          150460 non-null  int64
 1   inning            150460 non-null  int64
 2   batting_team      150460 non-null  str
 3   bowling_team      150460 non-null  str
 4   over              150460 non-null  int64
 5   ball              150460 non-null  int64
 6   batsman           150460 non-null  str
 7   non_striker       150460 non-null  str
 8   bowler            150460 non-null  str
 9   is_super_over     150460 non-null  int64
 10  wide_runs         150460 non-null  int64
 11  bye_runs          150460 non-null  int64
 12  legbye_runs       150460 non-null  int64
 13  noball_runs       150460 non-null  int64
 14  penalty_runs      150460 non-null  int64
 15  batsman_runs      150460 non-null  int64
 16  extra_runs        150460 non-null  int64
 17  total_runs        150460 non-null  int64
 18  player_dismissed  7438 non-null    str
 19  dismissal_kind    7438 non-null    str
 20  fielder           5369 non-null    str
dtypes: int64(13), str(8)
memory usage: 24.1 MB

In [14]:
df.describe()

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs
count,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000
mean,318.281317,1.482188,10.142649,3.616483,0.000538,0.037498,0.004885,0.022232,0.004340,0.000066,1.222445,0.069022,1.291466
std,182.955531,0.501768,5.674338,1.807698,0.023196,0.257398,0.114234,0.200104,0.072652,0.018229,1.594509,0.349667,1.583240
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,161.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,319.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,476.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,636.000000,4.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,6.000000,7.000000,7.000000

In [15]:
df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='str')

In [16]:
df.index

RangeIndex(start=0, stop=150460, step=1)

In [17]:
#indexing by rows and column
df[["match_id", "inning","bowling_team"]]

        match_id  inning                 bowling_team
0              1       1  Royal Challengers Bangalore
1              1       1  Royal Challengers Bangalore
2              1       1  Royal Challengers Bangalore
3              1       1  Royal Challengers Bangalore
4              1       1  Royal Challengers Bangalore
...          ...     ...                          ...
150455       636       2          Sunrisers Hyderabad
150456       636       2          Sunrisers Hyderabad
150457       636       2          Sunrisers Hyderabad
150458       636       2          Sunrisers Hyderabad
150459       636       2          Sunrisers Hyderabad

[150460 rows x 3 columns]

In [18]:
df.iloc[2]

match_id                                      1
inning                                        1
batting_team                Sunrisers Hyderabad
bowling_team        Royal Challengers Bangalore
over                                          1
ball                                          3
batsman                               DA Warner
non_striker                            S Dhawan
bowler                                 TS Mills
is_super_over                                 0
wide_runs                                     0
bye_runs                                      0
legbye_runs                                   0
noball_runs                                   0
penalty_runs                                  0
batsman_runs                                  4
extra_runs                                    0
total_runs                                    4
player_dismissed                            NaN
dismissal_kind                              NaN
fielder                                     NaN
Name: 2, dtype: object

In [19]:
list(df.iloc[1])

[np.int64(1),
 np.int64(1),
 'Sunrisers Hyderabad',
 'Royal Challengers Bangalore',
 np.int64(1),
 np.int64(2),
 'DA Warner',
 'S Dhawan',
 'TS Mills',
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 nan,
 nan,
 nan]

In [20]:
df[(df["batting_team"]=="Royal Challengers Bangalore") & (df["batsman"]== "CH Gayle")]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
125,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,Mandeep Singh,A Nehra,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
131,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,CH Gayle,Mandeep Singh,B Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
132,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,CH Gayle,Mandeep Singh,B Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
133,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,CH Gayle,Mandeep Singh,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
137,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,1,CH Gayle,Mandeep Singh,A Nehra,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150393,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,9,6,CH Gayle,V Kohli,MC Henriques,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150397,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,10,4,CH Gayle,V Kohli,Mustafizur Rahman,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150398,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,10,5,CH Gayle,V Kohli,Mustafizur Rahman,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150400,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,11,1,CH Gayle,V Kohli,BCJ Cutting,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150402,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,11,3,CH Gayle,V Kohli,BCJ Cutting,0,...,0,0,0,0,0,0,0,CH Gayle,caught,Bipul Sharma

In [21]:
df[(df["batting_team"]=="Royal Challengers Bangalore") | (df["batsman"]== "CH Gayle")]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
125,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,Mandeep Singh,A Nehra,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
126,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,CH Gayle,A Nehra,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
127,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,CH Gayle,A Nehra,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
128,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,CH Gayle,A Nehra,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
129,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,CH Gayle,A Nehra,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [22]:
df[df["legbye_runs"]==1]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
238,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,1,TS Mills,YS Chahal,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
309,2,1,Mumbai Indians,Rising Pune Supergiant,11,1,AT Rayudu,N Rana,A Zampa,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
383,2,2,Rising Pune Supergiant,Mumbai Indians,2,4,MA Agarwal,AM Rahane,HH Pandya,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
540,3,1,Gujarat Lions,Kolkata Knight Riders,8,3,BB McCullum,SK Raina,CR Woakes,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150337,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,CH Gayle,V Kohli,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150351,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,2,CH Gayle,V Kohli,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150446,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,5,STR Binny,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150451,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,4,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN

In [23]:
df[(df["bowler"].str.startswith("M")) & (df["ball"]==5) & (df["over"]==20) & (df["batsman"]=="BCJ Cutting")]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
147198,622,2,Sunrisers Hyderabad,Kings XI Punjab,20,5,BCJ Cutting,Yuvraj Singh,MM Sharma,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [24]:
df[(df["bowler"].str.endswith("n")) ]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
32,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,1,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
33,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,2,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
34,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,3,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
35,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,4,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
36,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,5,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150449,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,2,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150450,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,3,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150451,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,4,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150452,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,5,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150453,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [25]:
df[df["batsman"].isin(["Iqbal Abdulla","Sachin Baby"])]  #isin mean that the "Iqbal Abdulla","Sachin Baby" these both are present in the column or not

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
208,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,1,Sachin Baby,SR Watson,Bipul Sharma,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
209,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,2,Sachin Baby,SR Watson,Bipul Sharma,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
211,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,4,Sachin Baby,SR Watson,Bipul Sharma,0,...,0,0,0,0,0,0,0,Sachin Baby,caught,MC Henriques
1066,5,1,Royal Challengers Bangalore,Delhi Daredevils,18,1,Iqbal Abdulla,P Negi,CH Morris,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1067,5,1,Royal Challengers Bangalore,Delhi Daredevils,18,2,Iqbal Abdulla,P Negi,CH Morris,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [27]:
#update data
df.loc[df["bowler"]=="Sachin Baby"]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
146810,620,2,Gujarat Lions,Royal Challengers Bangalore,19,1,AJ Finch,PV Tambe,Sachin Baby,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
146811,620,2,Gujarat Lions,Royal Challengers Bangalore,19,2,AJ Finch,PV Tambe,Sachin Baby,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
146812,620,2,Gujarat Lions,Royal Challengers Bangalore,19,3,AJ Finch,PV Tambe,Sachin Baby,0,...,0,0,0,0,0,0,0,AJ Finch,caught,S Aravind
146813,620,2,Gujarat Lions,Royal Challengers Bangalore,19,4,S Kaushik,PV Tambe,Sachin Baby,0,...,0,0,0,0,0,0,0,S Kaushik,caught,S Aravind
148042,626,2,Kings XI Punjab,Royal Challengers Bangalore,13,1,MM Sharma,KC Cariappa,Sachin Baby,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
148043,626,2,Kings XI Punjab,Royal Challengers Bangalore,13,2,MM Sharma,KC Cariappa,Sachin Baby,0,...,0,0,0,0,0,0,0,MM Sharma,run out,SR Watson
148044,626,2,Kings XI Punjab,Royal Challengers Bangalore,13,3,KC Cariappa,Sandeep Sharma,Sachin Baby,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
148045,626,2,Kings XI Punjab,Royal Challengers Bangalore,13,4,Sandeep Sharma,KC Cariappa,Sachin Baby,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
148046,626,2,Kings XI Punjab,Royal Challengers Bangalore,13,5,KC Cariappa,Sandeep Sharma,Sachin Baby,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
148047,626,2,Kings XI Punjab,Royal Challengers Bangalore,13,6,Sandeep Sharma,KC Cariappa,Sachin Baby,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [30]:
#update data
df.loc[df["bowler"]=="Sachin Baby", "over"]=20  """.loc means the location-based indexer of a DataFrame.
                                                    It selects only those rows where the "bowler" column contains "Sachin Baby".
                                                    When we use .loc with an assignment, only the selected rows are updated in the DataFrame."""

In [29]:
df.loc[df["bowler"]=="Sachin Baby"]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
146810,620,2,Gujarat Lions,Royal Challengers Bangalore,20,1,AJ Finch,PV Tambe,Sachin Baby,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
146811,620,2,Gujarat Lions,Royal Challengers Bangalore,20,2,AJ Finch,PV Tambe,Sachin Baby,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
146812,620,2,Gujarat Lions,Royal Challengers Bangalore,20,3,AJ Finch,PV Tambe,Sachin Baby,0,...,0,0,0,0,0,0,0,AJ Finch,caught,S Aravind
146813,620,2,Gujarat Lions,Royal Challengers Bangalore,20,4,S Kaushik,PV Tambe,Sachin Baby,0,...,0,0,0,0,0,0,0,S Kaushik,caught,S Aravind
148042,626,2,Kings XI Punjab,Royal Challengers Bangalore,20,1,MM Sharma,KC Cariappa,Sachin Baby,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
148043,626,2,Kings XI Punjab,Royal Challengers Bangalore,20,2,MM Sharma,KC Cariappa,Sachin Baby,0,...,0,0,0,0,0,0,0,MM Sharma,run out,SR Watson
148044,626,2,Kings XI Punjab,Royal Challengers Bangalore,20,3,KC Cariappa,Sandeep Sharma,Sachin Baby,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
148045,626,2,Kings XI Punjab,Royal Challengers Bangalore,20,4,Sandeep Sharma,KC Cariappa,Sachin Baby,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
148046,626,2,Kings XI Punjab,Royal Challengers Bangalore,20,5,KC Cariappa,Sandeep Sharma,Sachin Baby,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
148047,626,2,Kings XI Punjab,Royal Challengers Bangalore,20,6,Sandeep Sharma,KC Cariappa,Sachin Baby,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [34]:
df.dropna()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
64,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,11,3,S Dhawan,MC Henriques,STR Binny,0,...,0,0,0,0,0,0,0,S Dhawan,caught,Sachin Baby
94,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,2,MC Henriques,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,0,0,0,MC Henriques,caught,Sachin Baby
165,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,3,CH Gayle,TM Head,DJ Hooda,0,...,0,0,0,0,0,0,0,CH Gayle,caught,DA Warner
199,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,4,KM Jadhav,TM Head,MC Henriques,0,...,0,0,0,0,1,0,1,KM Jadhav,run out,BCJ Cutting
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150402,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,11,3,CH Gayle,V Kohli,BCJ Cutting,0,...,0,0,0,0,0,0,0,CH Gayle,caught,Bipul Sharma
150422,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,5,AB de Villiers,KL Rahul,Bipul Sharma,0,...,0,0,0,0,0,0,0,AB de Villiers,caught,MC Henriques
150438,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,3,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,0,SR Watson,caught,MC Henriques
150448,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,1,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,1,0,1,STR Binny,run out,DJ Hooda
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha

In [39]:
df.fillna(0)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,0,0,0
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,0,0,0
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,0,0,0
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,0,0,0
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,0,0,0

In [40]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN